_target_: lightning.pytorch.Trainer
devices: ${devices}
accelerator: ${accelerator}
strategy: ${strategy}
log_every_n_steps: ${log_every_n_steps}
precision: ${precision}
accumulate_grad_batches: ${accumulate_grad_batches}
max_epochs: ${epoch}
