_target_: src.architectures.multimodal_architecture.MultiModalArchitecture

model:
  _target_: src.architectures.models.multimodal_transformer.MultiModalTransformer
  d_model: ${d_model}
  n_heads: ${n_heads}
  n_layers: ${n_layers}
  d_audio: 1024
  d_text: 1024
  n_classes: ${num_labels}
  attn_dropout: ${attn_dropout}
  relu_dropout: ${relu_dropout}
  res_dropout: ${res_dropout}
  emb_dropout: ${emb_dropout}
  out_dropout: ${out_dropout}
  attn_mask: ${attn_mask}
  scale_embedding: ${scale_embedding}

num_classes: ${num_labels}
average: macro
lr: ${lr}
t_max: ${t_max}
eta_min: ${eta_min}
interval: step
