_target_: src.architectures.multimodal_architecture.MultiModalArchitecture

model:
  _target_: src.architectures.models.multimodal_transformer.MultiModalTransformer
  model_dims: ${model_dims}
  num_heads: ${num_heads}
  num_layers: ${num_layers}
  audio_dims: 1024
  text_dims: 1024
  text_max_length: ${text_max_length}
  num_labels: ${num_labels}
  attn_dropout: ${attn_dropout}
  relu_dropout: ${relu_dropout}
  res_dropout: ${res_dropout}
  emb_dropout: ${emb_dropout}
  out_dropout: ${out_dropout}
  attn_mask: ${attn_mask}
  scale_embedding: ${scale_embedding}

num_labels: ${num_labels}
average: macro
strategy: ${strategy}
lr: ${lr}
weight_decay: ${weight_decay}
period: ${period}
eta_min: ${eta_min}
interval: step
