_target_: src.dataset.MultiModalDataset
data_path: '/content/path_data/path_train2.pkl'
pretrained_hubert: '/content/checkpoint/hubert_large/checkpoint-4110'
pretrained_roberta: '/content/checkpoint/roberta_large/checkpoint-4110'
audio_max_length: 80000
text_max_length: 249
num_labels: 7
audio_conv_kernel:
  - 10
  - 3
  - 3
  - 3
  - 3
  - 2
  - 2
audio_conv_stride:
  - 5
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
device: 'cuda:0'
