_target_: src.datasets.multimodal_dataset.KEMDy19Dataset
data_path: ${connected_dir}
split: ${split.train}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_hubert: ${connected_dir}/checkpoints/hubert_large/checkpoint-4110
pretrained_roberta: ${connected_dir}/checkpoints/roberta_large/checkpoint-4110
audio_max_length: 80000
text_max_length: ${text_max_length}
num_labels: ${num_labels}
audio_conv_kernel:
  - 10
  - 3
  - 3
  - 3
  - 3
  - 2
  - 2
audio_conv_stride:
  - 5
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
device: "cuda"
