_target_: src.datasets.text_dataset.KEMDy19Dataset
data_path: ${connected_dir}
split: ${split.train}
target_column_name: ${target_column_name}
pretrained_model: ${text_pretrained_model_name}
text_max_length: ${text_max_length}