model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val_MulticlassF1Score
  mode: max
  save_top_k: 3
  save_last: True
  verbose: True
  dirpath: ${project_dir}/checkpoints/${model_name}/${dataset_name}
  filename: ${save_detail}-epoch{epoch}
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val_MulticlassF1Score
  mode: max
  patience: 3
  min_delta: 0

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

rich_progress_bar:
