# @package _global_
defaults:
  - dataset_module: multimodal_kemdy_dataset
  - architecture_module: basic_multimodal_archimodule
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

seed: 2022

data_path:
  train: C:/project_Han/multimodal-transformer/path_data/path_train.pkl
  val: C:/project_Han/multimodal-transformer/path_data/path_val.pkl
  test: C:/project_Han/multimodal-transformer/path_data/path_test.pkl

batch_size: 48

d_model: 1024
n_heads: 8
n_layers: 4

lr: 0.00001

project_name: MultiModalTransformer
model_name: ${project_name}-d_model${d_model}-n_heads${n_heads}-n_layers${n_layers}

ckpt_folder: ${callbacks.model_checkpoint.dirpath}
ckpt_path: ${ckpt_folder}${model_name}-bs${batch_size}-epoch${epoch}.ckpt

run_name: ${model_name}-test
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 50
