# @package _global_
defaults:
  - dataset: multimodal_kemdy19_dataset
  - architecture: multimodal_architecture
  - tuner: multimodal_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

project_dir: /home/ddang/multimodal-transformer

seed: 2024

num_labels: 7

data_path:
  train: ${project_dir}/path_data/path_train.pkl
  val: ${project_dir}/path_data/path_val.pkl
  test: ${project_dir}/path_data/path_test.pkl

batch_size: 64

d_model: 1024
n_heads: 8
n_layers: 4
attn_dropout: .3
relu_dropout: .3
res_dropout: .3
emb_dropout: .3
out_dropout: .3
attn_mask: False
scale_embedding: True

lr: 0.00001
t_max: 50
eta_min: 0.0000025

epoch: 20

model_name: MultiModalTransformer
dataset_name: KEMDy19

is_tuned: True
num_trials: 3
hparams_save_path: ${project_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}
save_detail: d_model${d_model}-n_heads${n_heads}-n_layers${n_layers}-bs${batch_size}
ckpt_path: ${callbacks.model_checkpoint.dirpath}/${save_detail}-epoch${epoch}.ckpt

mode: train
run_name: ${project_name}-${mode}
work_dir: ${hydra:runtime.cwd}