# @package _global_
defaults:
  - dataset: multimodal_kemdy19_dataset
  - tuner: multimodal_tuner
  - hydra: hydra

project_dir: /home/ddang/multimodal-transformer

seed: 2024

num_labels: 7

data_path:
  train: ${project_dir}/path_data/path_train.pkl
  val: ${project_dir}/path_data/path_val.pkl
  test: ${project_dir}/path_data/path_test.pkl

batch_size: 64

num_trials: 3
save_path: ${project_dir}/hparams

dataset_name: KEMDy19
project_name: MultiModalTransformer
model_name: ${dataset_name}-${project_name}

run_name: ${model_name}-tune
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 10
