# @package _global_
defaults:
  - dataset: multimodal_kemdy19_dataset
  - architecture: multimodal_architecture
  - tuner: multimodal_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: multimodal-transformer
project_dir: /home/ddang/${package_name}
connected_dir: /data/${package_name}

seed: 2024

num_labels: 7

split:
  train: train
  val: val
  test: test

batch_size: 64

d_model: 1024
n_heads: 8
n_layers: 4
attn_dropout: .3
relu_dropout: .3
res_dropout: .3
emb_dropout: .3
out_dropout: .3
attn_mask: False
scale_embedding: True

lr: 0.00001
t_max: 50
eta_min: 0.0000025

monitor: val_MulticlassF1Score
tracking_direction: max
patience: 3
min_delta: 0

devices: -1
accelerator: gpu
strategy: ddp
log_every_n_steps: 10
precision: 32
epoch: 20

model_name: MultiModalTransformer
dataset_name: KEMDy19
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
save_detail: d_model${d_model}-n_heads${n_heads}-n_layers${n_layers}-bs${batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch${epoch}.ckpt

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}