# @package _global_
defaults:
  - dataset: multimodal_kemdy19_dataset
  - architecture: multimodal_architecture
  - tuner: multimodal_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: multimodal-transformer
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2024

num_labels: 7

split:
  train: train
  val: val
  test: test
  predict: predict

batch_size: 64

target_column_name: emotion
text_max_length: 249

model_dims: 1024
num_heads: 8
num_layers: 4
attn_dropout: .3
relu_dropout: .3
res_dropout: .3
emb_dropout: .3
out_dropout: .3
attn_mask: False
scale_embedding: True

lr: 0.0001
period: 2
eta_min: 0.00001

monitor: val_MulticlassF1Score
tracking_direction: max
patience: 2
min_delta: 0

devices: ${oc.decode:${oc.env:DEVICES}}
accelerator: gpu
strategy: ddp
log_every_n_steps: 10
precision: 32
accumulate_grad_batches: 1
gradient_clip_val: 1
gradient_clip_algorithm: norm
epoch: 20

model_name: MultiModalTransformer
dataset_name: KEMDy19
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs=${batch_size}x${devices}x${accumulate_grad_batches}
save_detail: model_dims=${model_dims}-num_heads=${num_heads}-num_layers=${num_layers}-precision=${precision}-${total_batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch=${epoch}.ckpt

submission_file_name: test
logit_name: ${save_detail}-epoch=${epoch}
submission_name: ${save_detail}-epoch=${epoch}

user_name: ${oc.env:USER_NAME}
upload_tag: multimodal-emotions
num_safetensors: 2

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}