# @package _global_
defaults:
  - dataset: dataset
  - pl_module: pl_module
  - logger: wandb
  - hydra: default.yaml
  - callbacks: default.yaml
  - trainer: default.yaml

data_path:
  train: '/content/path_data/path_train2.pkl'
  val: '/content/path_data/path_val2.pkl'
  test: '/content/path_data/path_test2.pkl'

batch_size: 16

model_name: MultiModalTransformer

seed: 2022

run_name: ${model_name}
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

wandb_api_key:  ${oc.env:wandb_api_key}

epoch: 50
