# @package _global_
defaults:
  - dataset: audio_kemdy19_dataset
  - training_arguments: training_arguments
  - hydra: hydra

project_dir: /home/ddang/multimodal-transformer

seed: 2024

num_labels: 7

data_path:
  train: ${project_dir}/path_data/path_train.pkl
  val: ${project_dir}/path_data/path_val.pkl
  test: ${project_dir}/path_data/path_test.pkl

batch_size: 32

audio_pretrained_model_name: facebook/hubert-large-ls960-ft
text_pretrained_model_name: klue/roberta-large

output_hidden_states: False

metric:
  first_metric: glue
  second_metric: mnli

lr: 0.00002

epoch: 5

model_name: UniModalTransformer
dataset_name: KEMDy19

project_name: ${model_name}-${dataset_name}
save_detail: bs${batch_size}-lr${lr}-epoch${epoch}

modality: audio
run_name: ${project_name}-${modality}
work_dir: ${hydra:runtime.cwd}

output_directory: ${project_dir}/checkpoints/${modality}
save_predictions: ${project_dir}/preds/unimodal