_target_: src.dataset_modules.multimodal_dataset.KEMDy19Dataset
data_path: ${project_dir}/path_data/path_train.pkl
pretrained_hubert: ${project_dir}/checkpoints/hubert_large/checkpoint-4110
pretrained_roberta: ${project_dir}/checkpoints/roberta_large/checkpoint-4110
audio_max_length: 80000
text_max_length: 249
num_labels: ${num_labels}
audio_conv_kernel:
  - 10
  - 3
  - 3
  - 3
  - 3
  - 2
  - 2
audio_conv_stride:
  - 5
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
device: "cuda"
